spring:
    cloud:
        openfeign:
            autoconfiguration:
                jackson:
                    enabled: true
    application:
        name: $CI_PROJECT_NAME
    datasource:
        hikari:
            connection-init-sql: set search_path to $DB_SCHEMA; set statement_timeout to $DB_STATEMENT_TIMEOUT;
            connection-test-query: select 1
            connection-timeout: 30000
            driver-class-name: org.postgresql.Driver
            idle-timeout: 30000
            max-lifetime: 40000
            maximum-pool-size: $DB_POOL_SIZE
            minimum-idle: $DB_POOL_MIN_SIZE
            pool-name: $DB_SERVER
            password: $DB_PASSWORD
            jdbc-url: jdbc:postgresql://$DB_SERVER:$DB_PORT/$DB_NAME?socketTimeout=$DB_SOCKET_TIMEOUT
            username: $DB_USER
springdoc:
    api-docs:
        enabled: $SWAGGER_ENABLED
    swagger-ui:
        enabled: $SWAGGER_ENABLED
